version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432"
  web:
    build: .
    container_name: web
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db