default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  # host: localhost
  database: sealth_vault_development
  username: postgres
  password: 12345
  pool: 5
  timeout: 5000
  

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
